services:
  nem-dashboard:
    image: zhipenghe/nem-dashboard:latest
    pull_policy: always
    container_name: nem-dashboard
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./data:/app/data
    restart: unless-stopped