name: Sync to Hugging Face Space

on:
  push:
    branches: [ 'main' ] 
    paths:
      - '.github/workflows/hf-spaces-sync.yml'
      - 'hf_spaces/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            hf_spaces
      
      - name: Sync to Hugging Face Spaces
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: ZhipengHe/NEM-Dashboard
          huggingface_repo_id: ZhipengHe/NEM-Dashboard
          repo_type: space
          space_sdk: docker
          subdirectory: hf_spaces
          hf_token: ${{ secrets.HF_TOKEN }}